---
- name: Клонирование репозитория на ноды группы [app]
  hosts: app
  become: true
  tasks:
    - name: Убедиться, что Git установлен
      apt:
        name: git
        state: present

    - name: Клонирование репозитория
      git:
        repo: https://github.com/mdn/django-locallibrary-tutorial.git
        dest: /opt/django-locallibrary
        version: main

- name: Установка nginx
  hosts: web
  become: true
  roles:
    - nginx
  vars:
    static_path: /opt/django-locallibrary/catalog/static/
    proxy_host: 127.0.0.1
    proxy_port: 8000

- name: Запуск Django-приложения через Docker
  hosts: app
  become: true
  roles:
    - Docker
  tasks:
    - name: Убедиться, что Docker запущен
      service:
        name: docker
        state: started
        enabled: true

    - name: Убедиться, что Docker Compose установлен
      apt:
        name: docker-compose
        state: present

    - name: Создать директорию для приложения
      ansible.builtin.file:
        path: /opt/django-locallibrary
        state: directory

    - name: Скопировать Dockerfile
      copy:
        src: ./Dockerfile
        dest: /opt/django-locallibrary/Dockerfile

    - name: Скопировать docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: /opt/django-locallibrary/docker-compose.yml

    - name: Запустить контейнеры
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: /opt/django-locallibrary

    - name: Назначить права для www-data на static files
      ansible.builtin.file:
        path: /opt/django-locallibrary/catalog/static
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Убедиться, что все файлы в static files доступны www-data
      ansible.builtin.command:
        cmd: chown -R www-data:www-data /opt/django-locallibrary/catalog/static
